/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.fluentqa.alt.client.JSON;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Set;

import io.fluentqa.alt.client.JSON;

/**
 * CreateSubmissionDataRequestData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-07T00:51:44.596816+08:00[Asia/Hong_Kong]")
public class CreateSubmissionDataRequestData {
  public static final String SERIALIZED_NAME_AUTH_PHONE_NUMBER_HASH = "auth_phone_number_hash";
  @SerializedName(SERIALIZED_NAME_AUTH_PHONE_NUMBER_HASH)
  private String authPhoneNumberHash;

  public static final String SERIALIZED_NAME_AUTH_PROVIDER = "auth_provider";
  @SerializedName(SERIALIZED_NAME_AUTH_PROVIDER)
  private String authProvider;

  /**
   * Gets or Sets authSecondFactorType
   */
  @JsonAdapter(AuthSecondFactorTypeEnum.Adapter.class)
  public enum AuthSecondFactorTypeEnum {
    NONE("none"),
    
    PHONE_NUMBER("phone_number"),
    
    TOTP("totp"),
    
    MOBILE_PUSH("mobile_push"),
    
    SECURITY_KEY("security_key"),
    
    FINGERPRINT("fingerprint");

    private String value;

    AuthSecondFactorTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AuthSecondFactorTypeEnum fromValue(String value) {
      for (AuthSecondFactorTypeEnum b : AuthSecondFactorTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AuthSecondFactorTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AuthSecondFactorTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AuthSecondFactorTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AuthSecondFactorTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_AUTH_SECOND_FACTOR_TYPE = "auth_second_factor_type";
  @SerializedName(SERIALIZED_NAME_AUTH_SECOND_FACTOR_TYPE)
  private AuthSecondFactorTypeEnum authSecondFactorType;

  public static final String SERIALIZED_NAME_AUTH_SESSION_ID_HASH = "auth_session_id_hash";
  @SerializedName(SERIALIZED_NAME_AUTH_SESSION_ID_HASH)
  private String authSessionIdHash;

  public static final String SERIALIZED_NAME_AUTH_SESSION_STARTED_AT = "auth_session_started_at";
  @SerializedName(SERIALIZED_NAME_AUTH_SESSION_STARTED_AT)
  private String authSessionStartedAt;

  /**
   * Gets or Sets authType
   */
  @JsonAdapter(AuthTypeEnum.Adapter.class)
  public enum AuthTypeEnum {
    NONE("none"),
    
    PASSWORD("password"),
    
    OAUTH("oauth"),
    
    EMAIL_LINK("email_link"),
    
    PHONE_NUMBER("phone_number"),
    
    LDAP("ldap"),
    
    SAML("saml");

    private String value;

    AuthTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AuthTypeEnum fromValue(String value) {
      for (AuthTypeEnum b : AuthTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AuthTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AuthTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AuthTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AuthTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_AUTH_TYPE = "auth_type";
  @SerializedName(SERIALIZED_NAME_AUTH_TYPE)
  private AuthTypeEnum authType;

  public static final String SERIALIZED_NAME_AUTH_USER_ID_HASH = "auth_user_id_hash";
  @SerializedName(SERIALIZED_NAME_AUTH_USER_ID_HASH)
  private String authUserIdHash;

  public static final String SERIALIZED_NAME_AUTH_USERNAME_HASH = "auth_username_hash";
  @SerializedName(SERIALIZED_NAME_AUTH_USERNAME_HASH)
  private String authUsernameHash;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<String> fields = null;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  private Integer order;

  public CreateSubmissionDataRequestData() { 
  }

  public CreateSubmissionDataRequestData authPhoneNumberHash(String authPhoneNumberHash) {
    
    this.authPhoneNumberHash = authPhoneNumberHash;
    return this;
  }

   /**
   * Get authPhoneNumberHash
   * @return authPhoneNumberHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthPhoneNumberHash() {
    return authPhoneNumberHash;
  }


  public void setAuthPhoneNumberHash(String authPhoneNumberHash) {
    this.authPhoneNumberHash = authPhoneNumberHash;
  }


  public CreateSubmissionDataRequestData authProvider(String authProvider) {
    
    this.authProvider = authProvider;
    return this;
  }

   /**
   * Get authProvider
   * @return authProvider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthProvider() {
    return authProvider;
  }


  public void setAuthProvider(String authProvider) {
    this.authProvider = authProvider;
  }


  public CreateSubmissionDataRequestData authSecondFactorType(AuthSecondFactorTypeEnum authSecondFactorType) {
    
    this.authSecondFactorType = authSecondFactorType;
    return this;
  }

   /**
   * Get authSecondFactorType
   * @return authSecondFactorType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AuthSecondFactorTypeEnum getAuthSecondFactorType() {
    return authSecondFactorType;
  }


  public void setAuthSecondFactorType(AuthSecondFactorTypeEnum authSecondFactorType) {
    this.authSecondFactorType = authSecondFactorType;
  }


  public CreateSubmissionDataRequestData authSessionIdHash(String authSessionIdHash) {
    
    this.authSessionIdHash = authSessionIdHash;
    return this;
  }

   /**
   * Get authSessionIdHash
   * @return authSessionIdHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthSessionIdHash() {
    return authSessionIdHash;
  }


  public void setAuthSessionIdHash(String authSessionIdHash) {
    this.authSessionIdHash = authSessionIdHash;
  }


  public CreateSubmissionDataRequestData authSessionStartedAt(String authSessionStartedAt) {
    
    this.authSessionStartedAt = authSessionStartedAt;
    return this;
  }

   /**
   * Get authSessionStartedAt
   * @return authSessionStartedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthSessionStartedAt() {
    return authSessionStartedAt;
  }


  public void setAuthSessionStartedAt(String authSessionStartedAt) {
    this.authSessionStartedAt = authSessionStartedAt;
  }


  public CreateSubmissionDataRequestData authType(AuthTypeEnum authType) {
    
    this.authType = authType;
    return this;
  }

   /**
   * Get authType
   * @return authType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public AuthTypeEnum getAuthType() {
    return authType;
  }


  public void setAuthType(AuthTypeEnum authType) {
    this.authType = authType;
  }


  public CreateSubmissionDataRequestData authUserIdHash(String authUserIdHash) {
    
    this.authUserIdHash = authUserIdHash;
    return this;
  }

   /**
   * Get authUserIdHash
   * @return authUserIdHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthUserIdHash() {
    return authUserIdHash;
  }


  public void setAuthUserIdHash(String authUserIdHash) {
    this.authUserIdHash = authUserIdHash;
  }


  public CreateSubmissionDataRequestData authUsernameHash(String authUsernameHash) {
    
    this.authUsernameHash = authUsernameHash;
    return this;
  }

   /**
   * Get authUsernameHash
   * @return authUsernameHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthUsernameHash() {
    return authUsernameHash;
  }


  public void setAuthUsernameHash(String authUsernameHash) {
    this.authUsernameHash = authUsernameHash;
  }


  public CreateSubmissionDataRequestData email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public CreateSubmissionDataRequestData fields(List<String> fields) {
    
    this.fields = fields;
    return this;
  }

  public CreateSubmissionDataRequestData addFieldsItem(String fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getFields() {
    return fields;
  }


  public void setFields(List<String> fields) {
    this.fields = fields;
  }


  public CreateSubmissionDataRequestData metadata(Object metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


  public CreateSubmissionDataRequestData name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CreateSubmissionDataRequestData order(Integer order) {
    
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getOrder() {
    return order;
  }


  public void setOrder(Integer order) {
    this.order = order;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSubmissionDataRequestData createSubmissionDataRequestData = (CreateSubmissionDataRequestData) o;
    return Objects.equals(this.authPhoneNumberHash, createSubmissionDataRequestData.authPhoneNumberHash) &&
        Objects.equals(this.authProvider, createSubmissionDataRequestData.authProvider) &&
        Objects.equals(this.authSecondFactorType, createSubmissionDataRequestData.authSecondFactorType) &&
        Objects.equals(this.authSessionIdHash, createSubmissionDataRequestData.authSessionIdHash) &&
        Objects.equals(this.authSessionStartedAt, createSubmissionDataRequestData.authSessionStartedAt) &&
        Objects.equals(this.authType, createSubmissionDataRequestData.authType) &&
        Objects.equals(this.authUserIdHash, createSubmissionDataRequestData.authUserIdHash) &&
        Objects.equals(this.authUsernameHash, createSubmissionDataRequestData.authUsernameHash) &&
        Objects.equals(this.email, createSubmissionDataRequestData.email) &&
        Objects.equals(this.fields, createSubmissionDataRequestData.fields) &&
        Objects.equals(this.metadata, createSubmissionDataRequestData.metadata) &&
        Objects.equals(this.name, createSubmissionDataRequestData.name) &&
        Objects.equals(this.order, createSubmissionDataRequestData.order);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(authPhoneNumberHash, authProvider, authSecondFactorType, authSessionIdHash, authSessionStartedAt, authType, authUserIdHash, authUsernameHash, email, fields, metadata, name, order);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSubmissionDataRequestData {\n");
    sb.append("    authPhoneNumberHash: ").append(toIndentedString(authPhoneNumberHash)).append("\n");
    sb.append("    authProvider: ").append(toIndentedString(authProvider)).append("\n");
    sb.append("    authSecondFactorType: ").append(toIndentedString(authSecondFactorType)).append("\n");
    sb.append("    authSessionIdHash: ").append(toIndentedString(authSessionIdHash)).append("\n");
    sb.append("    authSessionStartedAt: ").append(toIndentedString(authSessionStartedAt)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    authUserIdHash: ").append(toIndentedString(authUserIdHash)).append("\n");
    sb.append("    authUsernameHash: ").append(toIndentedString(authUsernameHash)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("auth_phone_number_hash");
    openapiFields.add("auth_provider");
    openapiFields.add("auth_second_factor_type");
    openapiFields.add("auth_session_id_hash");
    openapiFields.add("auth_session_started_at");
    openapiFields.add("auth_type");
    openapiFields.add("auth_user_id_hash");
    openapiFields.add("auth_username_hash");
    openapiFields.add("email");
    openapiFields.add("fields");
    openapiFields.add("metadata");
    openapiFields.add("name");
    openapiFields.add("order");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("auth_type");
    openapiRequiredFields.add("email");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CreateSubmissionDataRequestData
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (CreateSubmissionDataRequestData.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateSubmissionDataRequestData is not found in the empty JSON string", CreateSubmissionDataRequestData.openapiRequiredFields.toString()));
        }
      }
      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CreateSubmissionDataRequestData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateSubmissionDataRequestData` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateSubmissionDataRequestData.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateSubmissionDataRequestData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateSubmissionDataRequestData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateSubmissionDataRequestData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateSubmissionDataRequestData.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateSubmissionDataRequestData>() {
           @Override
           public void write(JsonWriter out, CreateSubmissionDataRequestData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateSubmissionDataRequestData read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateSubmissionDataRequestData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateSubmissionDataRequestData
  * @throws IOException if the JSON string is invalid with respect to CreateSubmissionDataRequestData
  */
  public static CreateSubmissionDataRequestData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateSubmissionDataRequestData.class);
  }

 /**
  * Convert an instance of CreateSubmissionDataRequestData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

