/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import io.fluentqa.alt.client.model.TemplatesTemplateIdAddFieldsFields;
import org.junit.Test;


/**
 * Model tests for AddFieldsData
 */
public class AddFieldsDataTest {
    private final AddFieldsData model = new AddFieldsData();

    /**
     * Model tests for AddFieldsData
     */
    @Test
    public void testAddFieldsData() {
        // TODO: test AddFieldsData
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

}
