/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for AuthenticationSuccessResponse
 */
public class AuthenticationSuccessResponseTest {
    private final AuthenticationSuccessResponse model = new AuthenticationSuccessResponse();

    /**
     * Model tests for AuthenticationSuccessResponse
     */
    @Test
    public void testAuthenticationSuccessResponse() {
        // TODO: test AuthenticationSuccessResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
