/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import io.fluentqa.alt.client.model.CombinedSubmissionAction;
import org.junit.Test;


/**
 * Model tests for CombinedSubmission
 */
public class CombinedSubmissionTest {
    private final CombinedSubmission model = new CombinedSubmission();

    /**
     * Model tests for CombinedSubmission
     */
    @Test
    public void testCombinedSubmission() {
        // TODO: test CombinedSubmission
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'expired'
     */
    @Test
    public void expiredTest() {
        // TODO: test expired
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'submissionIds'
     */
    @Test
    public void submissionIdsTest() {
        // TODO: test submissionIds
    }

    /**
     * Test the property 'sourcePdfs'
     */
    @Test
    public void sourcePdfsTest() {
        // TODO: test sourcePdfs
    }

    /**
     * Test the property 'downloadUrl'
     */
    @Test
    public void downloadUrlTest() {
        // TODO: test downloadUrl
    }

    /**
     * Test the property 'pdfHash'
     */
    @Test
    public void pdfHashTest() {
        // TODO: test pdfHash
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

}
