/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for CombinePdfsData
 */
public class CombinePdfsDataTest {
    private final CombinePdfsData model = new CombinePdfsData();

    /**
     * Model tests for CombinePdfsData
     */
    @Test
    public void testCombinePdfsData() {
        // TODO: test CombinePdfsData
    }

    /**
     * Test the property 'deleteCustomFiles'
     */
    @Test
    public void deleteCustomFilesTest() {
        // TODO: test deleteCustomFiles
    }

    /**
     * Test the property 'expiresIn'
     */
    @Test
    public void expiresInTest() {
        // TODO: test expiresIn
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'sourcePdfs'
     */
    @Test
    public void sourcePdfsTest() {
        // TODO: test sourcePdfs
    }

    /**
     * Test the property 'test'
     */
    @Test
    public void testTest() {
        // TODO: test test
    }

}
