/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for CopyTemplateData
 */
public class CopyTemplateDataTest {
    private final CopyTemplateData model = new CopyTemplateData();

    /**
     * Model tests for CopyTemplateData
     */
    @Test
    public void testCopyTemplateData() {
        // TODO: test CopyTemplateData
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'parentFolderId'
     */
    @Test
    public void parentFolderIdTest() {
        // TODO: test parentFolderId
    }

}
