/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for CreateSubmissionDataRequestTokenResponseToken
 */
public class CreateSubmissionDataRequestTokenResponseTokenTest {
    private final CreateSubmissionDataRequestTokenResponseToken model = new CreateSubmissionDataRequestTokenResponseToken();

    /**
     * Model tests for CreateSubmissionDataRequestTokenResponseToken
     */
    @Test
    public void testCreateSubmissionDataRequestTokenResponseToken() {
        // TODO: test CreateSubmissionDataRequestTokenResponseToken
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'secret'
     */
    @Test
    public void secretTest() {
        // TODO: test secret
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'dataRequestUrl'
     */
    @Test
    public void dataRequestUrlTest() {
        // TODO: test dataRequestUrl
    }

}
