/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for CreateCustomFileData
 */
public class CreateCustomFileDataTest {
    private final CreateCustomFileData model = new CreateCustomFileData();

    /**
     * Model tests for CreateCustomFileData
     */
    @Test
    public void testCreateCustomFileData() {
        // TODO: test CreateCustomFileData
    }

    /**
     * Test the property 'cacheId'
     */
    @Test
    public void cacheIdTest() {
        // TODO: test cacheId
    }

}
