/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import io.fluentqa.alt.client.model.UploadTemplateData;
import org.junit.Test;


/**
 * Model tests for CreateTemplateFromUploadData
 */
public class CreateTemplateFromUploadDataTest {
    private final CreateTemplateFromUploadData model = new CreateTemplateFromUploadData();

    /**
     * Model tests for CreateTemplateFromUploadData
     */
    @Test
    public void testCreateTemplateFromUploadData() {
        // TODO: test CreateTemplateFromUploadData
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

}
