/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import io.fluentqa.alt.client.model.FoldersFolder;
import org.junit.Test;


/**
 * Model tests for CreateFolderData
 */
public class CreateFolderDataTest {
    private final CreateFolderData model = new CreateFolderData();

    /**
     * Model tests for CreateFolderData
     */
    @Test
    public void testCreateFolderData() {
        // TODO: test CreateFolderData
    }

    /**
     * Test the property 'folder'
     */
    @Test
    public void folderTest() {
        // TODO: test folder
    }

}
