/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import io.fluentqa.alt.client.model.Submission;
import org.junit.Test;


/**
 * Model tests for CreateSubmissionResponse
 */
public class CreateSubmissionResponseTest {
    private final CreateSubmissionResponse model = new CreateSubmissionResponse();

    /**
     * Model tests for CreateSubmissionResponse
     */
    @Test
    public void testCreateSubmissionResponse() {
        // TODO: test CreateSubmissionResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'submission'
     */
    @Test
    public void submissionTest() {
        // TODO: test submission
    }

}
