/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for PendingTemplate
 */
public class PendingTemplateTest {
    private final PendingTemplate model = new PendingTemplate();

    /**
     * Model tests for PendingTemplate
     */
    @Test
    public void testPendingTemplate() {
        // TODO: test PendingTemplate
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'templateType'
     */
    @Test
    public void templateTypeTest() {
        // TODO: test templateType
    }

    /**
     * Test the property 'publicWebForm'
     */
    @Test
    public void publicWebFormTest() {
        // TODO: test publicWebForm
    }

    /**
     * Test the property 'publicSubmissions'
     */
    @Test
    public void publicSubmissionsTest() {
        // TODO: test publicSubmissions
    }

    /**
     * Test the property 'expireSubmissions'
     */
    @Test
    public void expireSubmissionsTest() {
        // TODO: test expireSubmissions
    }

    /**
     * Test the property 'expireAfter'
     */
    @Test
    public void expireAfterTest() {
        // TODO: test expireAfter
    }

    /**
     * Test the property 'locked'
     */
    @Test
    public void lockedTest() {
        // TODO: test locked
    }

    /**
     * Test the property 'expirationInterval'
     */
    @Test
    public void expirationIntervalTest() {
        // TODO: test expirationInterval
    }

    /**
     * Test the property 'allowAdditionalProperties'
     */
    @Test
    public void allowAdditionalPropertiesTest() {
        // TODO: test allowAdditionalProperties
    }

    /**
     * Test the property 'editableSubmissions'
     */
    @Test
    public void editableSubmissionsTest() {
        // TODO: test editableSubmissions
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    public void webhookUrlTest() {
        // TODO: test webhookUrl
    }

    /**
     * Test the property 'slackWebhookUrl'
     */
    @Test
    public void slackWebhookUrlTest() {
        // TODO: test slackWebhookUrl
    }

    /**
     * Test the property 'redirectUrl'
     */
    @Test
    public void redirectUrlTest() {
        // TODO: test redirectUrl
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'parentFolderId'
     */
    @Test
    public void parentFolderIdTest() {
        // TODO: test parentFolderId
    }

}
