/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for RenameFolderData
 */
public class RenameFolderDataTest {
    private final RenameFolderData model = new RenameFolderData();

    /**
     * Model tests for RenameFolderData
     */
    @Test
    public void testRenameFolderData() {
        // TODO: test RenameFolderData
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
