/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import io.fluentqa.alt.client.model.SubmissionDataBatchRequest;
import org.junit.Test;


/**
 * Model tests for SubmissionBatchData
 */
public class SubmissionBatchDataTest {
    private final SubmissionBatchData model = new SubmissionBatchData();

    /**
     * Model tests for SubmissionBatchData
     */
    @Test
    public void testSubmissionBatchData() {
        // TODO: test SubmissionBatchData
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'submissions'
     */
    @Test
    public void submissionsTest() {
        // TODO: test submissions
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    public void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'test'
     */
    @Test
    public void testTest() {
        // TODO: test test
    }

}
