/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for TemplateData
 */
public class TemplateDataTest {
    private final TemplateData model = new TemplateData();

    /**
     * Model tests for TemplateData
     */
    @Test
    public void testTemplateData() {
        // TODO: test TemplateData
    }

    /**
     * Test the property 'allowAdditionalProperties'
     */
    @Test
    public void allowAdditionalPropertiesTest() {
        // TODO: test allowAdditionalProperties
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'editableSubmissions'
     */
    @Test
    public void editableSubmissionsTest() {
        // TODO: test editableSubmissions
    }

    /**
     * Test the property 'expirationInterval'
     */
    @Test
    public void expirationIntervalTest() {
        // TODO: test expirationInterval
    }

    /**
     * Test the property 'expireAfter'
     */
    @Test
    public void expireAfterTest() {
        // TODO: test expireAfter
    }

    /**
     * Test the property 'expireSubmissions'
     */
    @Test
    public void expireSubmissionsTest() {
        // TODO: test expireSubmissions
    }

    /**
     * Test the property 'footerHtml'
     */
    @Test
    public void footerHtmlTest() {
        // TODO: test footerHtml
    }

    /**
     * Test the property 'headerHtml'
     */
    @Test
    public void headerHtmlTest() {
        // TODO: test headerHtml
    }

    /**
     * Test the property 'html'
     */
    @Test
    public void htmlTest() {
        // TODO: test html
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'publicSubmissions'
     */
    @Test
    public void publicSubmissionsTest() {
        // TODO: test publicSubmissions
    }

    /**
     * Test the property 'publicWebForm'
     */
    @Test
    public void publicWebFormTest() {
        // TODO: test publicWebForm
    }

    /**
     * Test the property 'redirectUrl'
     */
    @Test
    public void redirectUrlTest() {
        // TODO: test redirectUrl
    }

    /**
     * Test the property 'scss'
     */
    @Test
    public void scssTest() {
        // TODO: test scss
    }

    /**
     * Test the property 'slackWebhookUrl'
     */
    @Test
    public void slackWebhookUrlTest() {
        // TODO: test slackWebhookUrl
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    public void webhookUrlTest() {
        // TODO: test webhookUrl
    }

}
