/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for UpdateTemplateResponse
 */
public class UpdateTemplateResponseTest {
    private final UpdateTemplateResponse model = new UpdateTemplateResponse();

    /**
     * Model tests for UpdateTemplateResponse
     */
    @Test
    public void testUpdateTemplateResponse() {
        // TODO: test UpdateTemplateResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
