/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for UpdateSubmissionDataRequestData
 */
public class UpdateSubmissionDataRequestDataTest {
    private final UpdateSubmissionDataRequestData model = new UpdateSubmissionDataRequestData();

    /**
     * Model tests for UpdateSubmissionDataRequestData
     */
    @Test
    public void testUpdateSubmissionDataRequestData() {
        // TODO: test UpdateSubmissionDataRequestData
    }

    /**
     * Test the property 'authPhoneNumberHash'
     */
    @Test
    public void authPhoneNumberHashTest() {
        // TODO: test authPhoneNumberHash
    }

    /**
     * Test the property 'authProvider'
     */
    @Test
    public void authProviderTest() {
        // TODO: test authProvider
    }

    /**
     * Test the property 'authSecondFactorType'
     */
    @Test
    public void authSecondFactorTypeTest() {
        // TODO: test authSecondFactorType
    }

    /**
     * Test the property 'authSessionIdHash'
     */
    @Test
    public void authSessionIdHashTest() {
        // TODO: test authSessionIdHash
    }

    /**
     * Test the property 'authSessionStartedAt'
     */
    @Test
    public void authSessionStartedAtTest() {
        // TODO: test authSessionStartedAt
    }

    /**
     * Test the property 'authType'
     */
    @Test
    public void authTypeTest() {
        // TODO: test authType
    }

    /**
     * Test the property 'authUserIdHash'
     */
    @Test
    public void authUserIdHashTest() {
        // TODO: test authUserIdHash
    }

    /**
     * Test the property 'authUsernameHash'
     */
    @Test
    public void authUsernameHashTest() {
        // TODO: test authUsernameHash
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

}
