/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import io.fluentqa.alt.client.model.TemplateData;
import org.junit.Test;


/**
 * Model tests for UpdateTemplateData
 */
public class UpdateTemplateDataTest {
    private final UpdateTemplateData model = new UpdateTemplateData();

    /**
     * Model tests for UpdateTemplateData
     */
    @Test
    public void testUpdateTemplateData() {
        // TODO: test UpdateTemplateData
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

}
