/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for UploadTemplateDataDocumentMetadata
 */
public class UploadTemplateDataDocumentMetadataTest {
    private final UploadTemplateDataDocumentMetadata model = new UploadTemplateDataDocumentMetadata();

    /**
     * Model tests for UploadTemplateDataDocumentMetadata
     */
    @Test
    public void testUploadTemplateDataDocumentMetadata() {
        // TODO: test UploadTemplateDataDocumentMetadata
    }

    /**
     * Test the property 'filename'
     */
    @Test
    public void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'mimeType'
     */
    @Test
    public void mimeTypeTest() {
        // TODO: test mimeType
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

}
