/*
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.fluentqa.alt.client.model;

import org.junit.Test;


/**
 * Model tests for UploadPresignFields
 */
public class UploadPresignFieldsTest {
    private final UploadPresignFields model = new UploadPresignFields();

    /**
     * Model tests for UploadPresignFields
     */
    @Test
    public void testUploadPresignFields() {
        // TODO: test UploadPresignFields
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'policy'
     */
    @Test
    public void policyTest() {
        // TODO: test policy
    }

    /**
     * Test the property 'xAmzAlgorithm'
     */
    @Test
    public void xAmzAlgorithmTest() {
        // TODO: test xAmzAlgorithm
    }

    /**
     * Test the property 'xAmzCredential'
     */
    @Test
    public void xAmzCredentialTest() {
        // TODO: test xAmzCredential
    }

    /**
     * Test the property 'xAmzDate'
     */
    @Test
    public void xAmzDateTest() {
        // TODO: test xAmzDate
    }

    /**
     * Test the property 'xAmzSignature'
     */
    @Test
    public void xAmzSignatureTest() {
        // TODO: test xAmzSignature
    }

}
